export const DOC_LIST = [
  { id: '01-executive-summary', title: 'Executive Summary' },
  { id: '02-vision-mission-values', title: 'Vision, Mission & Values' },
  { id: '03-problem-statement', title: 'Problem Statement' },
  { id: '04-market-thesis', title: 'Market Thesis' },
  { id: '05-solution-architecture', title: 'Solution Architecture' },
  { id: '06-what-we-are-and-are-not', title: "What We Are and Aren't" },
  { id: '07-business-model', title: 'Business Model' },
  { id: '08-go-to-market', title: 'Go To Market' },
  { id: '09-roadmap-36-months', title: 'Roadmap 36 Months' },
  { id: '10-technology-strategy', title: 'Technology Strategy' },
  { id: '11-regulatory-strategy', title: 'Regulatory Strategy' },
  { id: '12-competitive-landscape', title: 'Competitive Landscape' },
  { id: '13-moat-and-defensibility', title: 'Moat and Defensibility' },
  { id: '14-unit-economics', title: 'Unit Economics' },
  { id: '15-risk-analysis', title: 'Risk Analysis' },
  { id: '16-fundraising-strategy', title: 'Fundraising Strategy' },
  { id: '17-appendix', title: 'Appendix' },
  { id: 'plano-negocios-kb', title: 'Plano de Negócios (KB)' },
];
