export const DOC_LIST = [
  { id: '01-executive-summary' },
  { id: '02-vision-mission-values' },
  { id: '03-problem-statement' },
  { id: '04-market-thesis' },
  { id: '05-solution-architecture' },
  { id: '06-what-we-are-and-are-not' },
  { id: '07-business-model' },
  { id: '08-go-to-market' },
  { id: '09-roadmap-36-months' },
  { id: '10-technology-strategy' },
  { id: '11-regulatory-strategy' },
  { id: '12-competitive-landscape' },
  { id: '13-moat-and-defensibility' },
  { id: '14-unit-economics' },
  { id: '15-risk-analysis' },
  { id: '16-fundraising-strategy' },
  { id: '17-appendix' },
  { id: 'plano-negocios-kb' },
];
