export const DOC_LIST = [
  { id: '01-executive-summary' },
  { id: '02-vision-mission-values' },
  { id: '03-problem-statement' },
  { id: '04-market-thesis' },
  { id: '05-solution-architecture' },
  { id: '06-what-we-are-and-are-not' },
  { id: '10-business-model' },
  { id: '11-go-to-market' },
  { id: '21-roadmap-36-months' },
  { id: '09-technology-strategy' },
  { id: '17-regulatory-strategy' },
  { id: '14-competitive-landscape' },
  { id: '15-infrastructure-moat' },
  { id: '18-unit-economics' },
  { id: '19-risk-analysis' },
  { id: '20-fundraising-strategy' },
  { id: '22-appendix' },
  { id: 'plano-negocios-kb' },
];
